### PR TITLE
Remove whole banning mechanism from gpos

### PR DESCRIPTION
**Pull request by hsyuan**
gpos has a set of banned API calls which needs to be allowed with the
ALLOW_xxx macro in order for gpopt to compile. But I think it is the
library caller(GPDB/Orca)'s resposibility to take care of the function call.

see discussions on https://github.com/greenplum-db/gpdb/pull/1136
and https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/Mcw6JPav6h4

I would prefer removing banned api for both gpdb and libc functions, instead of 
removing banned api for standard libc functions only.

### CODE REVIEW

**Comment by hsyuan** [comment]
@vraghavan78 @d @hlinnaka @danielgustafsson Please take a look.

**Comment by hlinnaka** [comment]
+1.

There are  more "#define ALLOW_*" lines in the tree, would be good to do a "grep ALLOW" and remove them all.

**Comment by danielgustafsson** [comment]
Yes please! 👍  🍰 🎉 You need a corresponding PR for Github to clean out the ALLOW overrides as well.

**Comment by vraghavan78** [comment]
You need to fix:

```
/libgpos/src/common/clibwrapper.cpp
/libgpos/src/common/pthreadwrapper.cpp
/libgpos/src/common/pthreadwrapper.cpp
/libgpos/src/common/syslibwrapper.cpp
/libgpos/src/io/ioutils.cpp
/libgpos/src/net/netutils.cpp
```

**Comment by vraghavan78** [comment]
Please clean up GPORCA:

```
./libgpopt/src/xforms/CXformUtils.cpp
./libnaucrates/src/CDXLUtils.cpp
./libnaucrates/src/operators/CDXLOperatorFactory.cpp
./server/src/unittest/dxl/CParseHandlerTest.cpp
./server/src/unittest/gpopt/operators/CExpressionPreprocessorTest.cpp
```

**Comment by hsyuan** [comment]
Will do.

**Pull request merged**
